repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: pixi-dependency-sync
        name: Pixi Dependency Sync
        entry: python ./dev/pyproject_check_dependencies.py
        language: system
