# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    create_environment:
      - curl -Ls https://pixi.sh/install.sh | bash
    install:
      - echo "$HOME"
      - echo "$PATH" | tr ":" "\n"
      - export PATH="$HOME/.pixi/bin:$PATH"
      - pixi install --environment doc
    build:
      html:
        - export PATH="$HOME/.pixi/bin:$PATH"
        - pixi run --environment doc docs
sphinx:
  configuration: docs/conf.py
