[project]
authors = [{name = "Paul Gierz", email = "pgierz@awi.de"}]
dependencies = []
name = "slurm-monitoring"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
slurm_monitoring = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
dlt = ">=1.5.0,<2"
streamlit = ">=1.44.1,<2"
duckdb = ">=1.2.2,<2"

