---
- name: reload prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: reloaded
  listen: reload prometheus

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    daemon_reload: true
  listen: restart prometheus

- name: restart alertmanager
  ansible.builtin.systemd:
    name: prometheus-alertmanager
    state: restarted
    daemon_reload: true
  listen: restart alertmanager

- name: restart grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
    daemon_reload: true
  listen: restart grafana
