"""Runtime configuration loaded from env vars and an optional YAML file.

All settings are keyed under the ``SLURM_MONITOR_`` prefix. A YAML file may
also be supplied via ``SLURM_MONITOR_CONFIG_FILE``; values from the file are
overridden by environment variables.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import yaml
from pydantic import Field, HttpUrl, SecretStr, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class AuthConfig(BaseSettings):
    """slurmrestd authentication.

    Albedo uses JWT auth. The token can be supplied directly, read from a
    file that is updated by a sidecar (preferred for long-running services),
    or generated by shelling out to ``scontrol token`` on a host that is
    inside the Munge trust domain.
    """

    model_config = SettingsConfigDict(env_prefix="SLURM_MONITOR_AUTH_", extra="ignore")

    user: str = Field(default="slurm", description="Slurm user the JWT is issued for.")
    token: SecretStr | None = Field(default=None, description="Static JWT (avoid in prod).")
    token_file: Path | None = Field(
        default=None,
        description="File whose contents are the current JWT. Re-read on every refresh.",
    )
    refresh_command: str | None = Field(
        default=None,
        description="Shell command that prints a fresh JWT on stdout (e.g. 'scontrol token lifespan=900').",
    )
    refresh_interval_seconds: int = Field(
        default=600, ge=30, description="How often to refresh via token_file or refresh_command."
    )


class SlurmConfig(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="SLURM_MONITOR_SLURM_", extra="ignore")

    base_url: HttpUrl = Field(
        default=HttpUrl("http://127.0.0.1:6820"),
        description="slurmrestd base URL. Use https:// in production.",
    )
    api_version: str | None = Field(
        default=None,
        description="Pin a specific OpenAPI version (e.g. 'v0.0.39'). Auto-detected when unset.",
    )
    timeout_seconds: float = Field(default=15.0, gt=0)
    verify_tls: bool = Field(default=True)
    ca_bundle: Path | None = Field(default=None)
    cluster: str = Field(default="albedo", description="Value emitted as the 'cluster' label.")


class CollectorIntervals(BaseSettings):
    """How often each collector polls slurmrestd.

    Tuned to keep total scheduler load well under 1 RPS even during outages,
    while still surfacing node-state changes promptly.
    """

    model_config = SettingsConfigDict(env_prefix="SLURM_MONITOR_INTERVAL_", extra="ignore")

    nodes_seconds: int = Field(default=20, ge=5)
    jobs_seconds: int = Field(default=30, ge=5)
    partitions_seconds: int = Field(default=60, ge=10)
    diag_seconds: int = Field(default=30, ge=5)
    reservations_seconds: int = Field(default=120, ge=30)


class ServerConfig(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="SLURM_MONITOR_SERVER_", extra="ignore")

    bind_host: str = Field(default="0.0.0.0")
    bind_port: int = Field(default=9817, ge=1, le=65535)
    log_level: str = Field(default="INFO")
    log_json: bool = Field(default=True)
    readiness_grace_seconds: int = Field(
        default=180,
        description="Time after startup during which /readyz is permissive.",
    )


class Settings(BaseSettings):
    """Top-level settings aggregator."""

    model_config = SettingsConfigDict(env_prefix="SLURM_MONITOR_", extra="ignore")

    config_file: Path | None = None

    auth: AuthConfig = Field(default_factory=AuthConfig)
    slurm: SlurmConfig = Field(default_factory=SlurmConfig)
    intervals: CollectorIntervals = Field(default_factory=CollectorIntervals)
    server: ServerConfig = Field(default_factory=ServerConfig)

    @field_validator("config_file", mode="before")
    @classmethod
    def _empty_to_none(cls, v: Any) -> Any:
        if v in ("", None):
            return None
        return v


def _strip_env_overridden(data: dict[str, Any], env_prefix: str) -> dict[str, Any]:
    """Drop keys whose ``<env_prefix><KEY>`` is already set in the environment.

    Pydantic prioritises ``__init__`` kwargs over env vars, so we have to
    strip env-set keys from the YAML data before passing it as kwargs;
    otherwise the file silently wins.
    """

    return {k: v for k, v in data.items() if f"{env_prefix}{k.upper()}" not in os.environ}


def load_settings() -> Settings:
    """Load settings, layering optional YAML under environment overrides.

    Precedence: env > YAML > defaults.
    """

    config_file = os.environ.get("SLURM_MONITOR_CONFIG_FILE")
    file_data: dict[str, Any] = {}
    if config_file:
        path = Path(config_file)
        if path.is_file():
            file_data = yaml.safe_load(path.read_text()) or {}

    auth = AuthConfig(**_strip_env_overridden(file_data.get("auth", {}), "SLURM_MONITOR_AUTH_"))
    slurm = SlurmConfig(**_strip_env_overridden(file_data.get("slurm", {}), "SLURM_MONITOR_SLURM_"))
    intervals = CollectorIntervals(
        **_strip_env_overridden(file_data.get("intervals", {}), "SLURM_MONITOR_INTERVAL_")
    )
    server = ServerConfig(
        **_strip_env_overridden(file_data.get("server", {}), "SLURM_MONITOR_SERVER_")
    )

    return Settings(
        config_file=Path(config_file) if config_file else None,
        auth=auth,
        slurm=slurm,
        intervals=intervals,
        server=server,
    )
