name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Project
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Check CLI
        run: slurm-monitor
  test-development-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.8
      - name: Check CLI
        run: pixi run slurm-monitor
